### ISSUE TITLE
SinisterGh0st's Issue

### ISSUE THREAD

**Issue by Jetaime-Alexandria** [Unicorns-Creations/MonoLauncher#10]
Constant JS error popup

I really like this so far though. Will be interesting to see what else gets implemented.
![Screenshot_1](https://user-images.githubusercontent.com/29360134/124018885-59df1700-d9b6-11eb-89a9-9d3509d5d782.png)

- SinisterGh0st

**Comment by JacubRSTNC** [comment]
Should be fixed with the latest update 🤷
